apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: nsaqui4c/fibonacci_client
      ports: 
       - containerPort: 3000